# Generated by Django 3.2.5 on 2021-07-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/channel/logo/'),
        ),
    ]
